<!DOCTYPE html>
<html lang="en">

<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Document</title>
</head>

<body>
    <script>
        // 在17-5-01里面已经实现了promise实例立即调用resolve或reject
        // 实例的状态status也立即发生改变的情况下
        // 如果在then的回调函数里面出现了错误，如未定义变量等
        // 会通过try catch统一调用onRejected进行错误处理

        // 那么上个例子的延时改变状态，status不立即发送变化的情况下
        // 如果出现未定义变量的错误，在then的内置函数里不会走到try catch
        // 也就无法处理错误
        class Hd {
            static PENDING = "pending"
            static FULFILLED = "fulfilled"
            static REJECTED = "rejected"
            constructor(executor) {
                this.status = Hd.PENDING
                this.value = null
                this.callbacks = []
                try {
                    executor(this.resolve.bind(this),
                        this.reject.bind(this))
                } catch (error) {
                    this.reject(error)
                }
            }
            resolve(value) {
                console.log(333)
                if (this.status == Hd.PENDING) {
                    this.value = value
                    this.status = Hd.FULFILLED
                }

                if (this.callbacks.length)
                    this.callbacks[0].onFulfilled(value)

            }
            reject(reason) {
                if (this.status == Hd.PENDING) {
                    this.value = reason
                    this.status = Hd.REJECTED
                }

                if (this.callbacks.length)
                    this.callbacks[0].onRejected(reason)
            }

            then(onFulfilled, onRejected) {
                console.log(1)
                if (!(onFulfilled instanceof Function)) {
                    onFulfilled = () => {}
                }
                if (!(onRejected instanceof Function)) {
                    onRejected = () => {}
                }


                console.log(this.status)

                if (this.status == Hd.PENDING) {
                    this.callbacks.push({
                        onFulfilled,
                        onRejected
                    })
                    console.log(this.callbacks)
                }

                // 在这里可以看到，then的两个回调函数在
                // 立即改变状态的情况下的错误处理
                if (this.status == Hd.FULFILLED) {
                    setTimeout(() => {
                        try {
                            onFulfilled(this.value)
                        } catch (error) {
                            onRejected(error)
                        }
                    })
                }
                if (this.status == Hd.REJECTED) {
                    setTimeout(() => {
                        try {
                            onRejected(this.value)
                        } catch (error) {
                            onRejected(error) // 待定
                        }
                    })
                }
            }
        }

        let promise = new Hd((resolve, reject) => {
                setTimeout(() => {
                    console.log('执行resolve前的操作')
                    resolve('解决')
                }, 1000)

                // setTimeout(() => {
                //     console.log('执行reject前的操作')
                //     reject('拒绝')
                // }, 1000)

            })
            .then((val) => {
                aaa
                console.log(val)
            }, (reason) => {
                console.log(reason)
            })

        console.log('houdunren')
    </script>
</body>

</html>